### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by hectorcapulin** [anseki/jquery-ui-autocomplete-scroll#4]
I recently used this library which is great, but I have a necessity: change the font size in the scroll, there's a way to do it?

**Comment by anseki** [comment]
Hi @hectorcapulin, thank you for the comment.

This library is a plugin for jQuery UI.
That is, of course yes, you can specify font size because the jQuery UI supports it.

For example, you can specify a "Size" of "Font Settings" in [ThemeRoller](http://jqueryui.com/themeroller/) if you used it for your theme.
Or, you can specify a `font-size` simply in your CSS.
Try this:

```css
.ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content {
  font-size: 2em;
}
```
